import { LanguageMapping } from '../..';

interface Language {
    name: string;
    twoLettersCode: string;
    threeLettersCode: string;
    locale: string;
    androidCode: string;
    osxCode: string;
    osxLocale: string;
}

type Mapper<I, O> = (input: I) => O;

const languagePlaceholders: { [placeholder: string]: Mapper<Language, string> } = {
    '%language%': lang => lang.name,
    '%two_letters_code%': lang => lang.twoLettersCode,
    '%three_letters_code%': lang => lang.threeLettersCode,
    '%locale%': lang => lang.locale,
    '%locale_with_underscore%': lang => lang.locale.replace(/-/g, '_'),
    '%android_code%': lang => lang.androidCode,
    '%osx_code%': lang => lang.osxCode,
    '%osx_locale%': lang => lang.osxLocale,
};

const languages: Language[] = [
    {
        name: 'Acholi',
        twoLettersCode: 'ach',
        threeLettersCode: 'ach',
        locale: 'ach-UG',
        androidCode: 'ach-rUG',
        osxCode: 'ach.lproj',
        osxLocale: 'ach',
    },
    {
        name: 'Afar',
        twoLettersCode: 'aa',
        threeLettersCode: 'aar',
        locale: 'aa-ER',
        androidCode: 'aa-rER',
        osxCode: 'aa.lproj',
        osxLocale: 'aa',
    },
    {
        name: 'Afrikaans',
        twoLettersCode: 'af',
        threeLettersCode: 'afr',
        locale: 'af-ZA',
        androidCode: 'af-rZA',
        osxCode: 'af.lproj',
        osxLocale: 'af',
    },
    {
        name: 'Akan',
        twoLettersCode: 'ak',
        threeLettersCode: 'aka',
        locale: 'ak-GH',
        androidCode: 'ak-rGH',
        osxCode: 'ak.lproj',
        osxLocale: 'ak',
    },
    {
        name: 'Akan, Twi',
        twoLettersCode: 'tw',
        threeLettersCode: 'twi',
        locale: 'tw-TW',
        androidCode: 'tw-rTW',
        osxCode: 'tw.lproj',
        osxLocale: 'tw',
    },
    {
        name: 'Albanian',
        twoLettersCode: 'sq',
        threeLettersCode: 'sqi',
        locale: 'sq-AL',
        androidCode: 'sq-rAL',
        osxCode: 'sq.lproj',
        osxLocale: 'sq',
    },
    {
        name: 'Amharic',
        twoLettersCode: 'am',
        threeLettersCode: 'amh',
        locale: 'am-ET',
        androidCode: 'am-rET',
        osxCode: 'am.lproj',
        osxLocale: 'am',
    },
    {
        name: 'Arabic',
        twoLettersCode: 'ar',
        threeLettersCode: 'ara',
        locale: 'ar-SA',
        androidCode: 'ar-rSA',
        osxCode: 'ar.lproj',
        osxLocale: 'ar',
    },
    {
        name: 'Arabic, Bahrain',
        twoLettersCode: 'ar',
        threeLettersCode: 'ara',
        locale: 'ar-BH',
        androidCode: 'ar-rBH',
        osxCode: 'ar-BH.lproj',
        osxLocale: 'ar_BH',
    },
    {
        name: 'Arabic, Egypt',
        twoLettersCode: 'ar',
        threeLettersCode: 'ara',
        locale: 'ar-EG',
        androidCode: 'ar-rEG',
        osxCode: 'ar-EG.lproj',
        osxLocale: 'ar_EG',
    },
    {
        name: 'Arabic, Saudi Arabia',
        twoLettersCode: 'ar',
        threeLettersCode: 'ara',
        locale: 'ar-SA',
        androidCode: 'ar-rSA',
        osxCode: 'ar-SA.lproj',
        osxLocale: 'ar_SA',
    },
    {
        name: 'Arabic, Yemen',
        twoLettersCode: 'ar',
        threeLettersCode: 'ara',
        locale: 'ar-YE',
        androidCode: 'ar-rYE',
        osxCode: 'ar-YE.lproj',
        osxLocale: 'ar_YE',
    },
    {
        name: 'Aragonese',
        twoLettersCode: 'an',
        threeLettersCode: 'arg',
        locale: 'an-ES',
        androidCode: 'an-rES',
        osxCode: 'an.lproj',
        osxLocale: 'an',
    },
    {
        name: 'Armenian',
        twoLettersCode: 'hy',
        threeLettersCode: 'hye',
        locale: 'hy-AM',
        androidCode: 'hy-rAM',
        osxCode: 'hy.lproj',
        osxLocale: 'hy',
    },
    {
        name: 'Arpitan',
        twoLettersCode: 'frp',
        threeLettersCode: 'frp',
        locale: 'frp-IT',
        androidCode: 'frp-rIT',
        osxCode: 'frp.lproj',
        osxLocale: 'frp',
    },
    {
        name: 'Assamese',
        twoLettersCode: 'as',
        threeLettersCode: 'asm',
        locale: 'as-IN',
        androidCode: 'as-rIN',
        osxCode: 'as.lproj',
        osxLocale: 'as',
    },
    {
        name: 'Asturian',
        twoLettersCode: 'ast',
        threeLettersCode: 'ast',
        locale: 'ast-ES',
        androidCode: 'ast-rES',
        osxCode: 'ast.lproj',
        osxLocale: 'ast',
    },
    {
        name: 'Atayal',
        twoLettersCode: 'tay',
        threeLettersCode: 'tay',
        locale: 'tay-TW',
        androidCode: 'tay-rTW',
        osxCode: 'tay.lproj',
        osxLocale: 'tay',
    },
    {
        name: 'Avaric',
        twoLettersCode: 'av',
        threeLettersCode: 'ava',
        locale: 'av-DA',
        androidCode: 'av-rDA',
        osxCode: 'av.lproj',
        osxLocale: 'av',
    },
    {
        name: 'Avestan',
        twoLettersCode: 'ae',
        threeLettersCode: 'ave',
        locale: 'ae-IR',
        androidCode: 'ae-rIR',
        osxCode: 'ae.lproj',
        osxLocale: 'ae',
    },
    {
        name: 'Aymara',
        twoLettersCode: 'ay',
        threeLettersCode: 'aym',
        locale: 'ay-BO',
        androidCode: 'ay-rBO',
        osxCode: 'ay.lproj',
        osxLocale: 'ay',
    },
    {
        name: 'Azerbaijani',
        twoLettersCode: 'az',
        threeLettersCode: 'aze',
        locale: 'az-AZ',
        androidCode: 'az-rAZ',
        osxCode: 'az.lproj',
        osxLocale: 'az',
    },
    {
        name: 'Balinese',
        twoLettersCode: 'ban',
        threeLettersCode: 'ban',
        locale: 'ban-ID',
        androidCode: 'ban-rID',
        osxCode: 'ban.lproj',
        osxLocale: 'ban',
    },
    {
        name: 'Balochi',
        twoLettersCode: 'bal',
        threeLettersCode: 'bal',
        locale: 'bal-BA',
        androidCode: 'bal-rBA',
        osxCode: 'bal.lproj',
        osxLocale: 'bal',
    },
    {
        name: 'Bambara',
        twoLettersCode: 'bm',
        threeLettersCode: 'bam',
        locale: 'bm-ML',
        androidCode: 'bm-rML',
        osxCode: 'bm.lproj',
        osxLocale: 'bm',
    },
    {
        name: 'Bashkir',
        twoLettersCode: 'ba',
        threeLettersCode: 'bak',
        locale: 'ba-RU',
        androidCode: 'ba-rRU',
        osxCode: 'ba.lproj',
        osxLocale: 'ba',
    },
    {
        name: 'Basque',
        twoLettersCode: 'eu',
        threeLettersCode: 'eus',
        locale: 'eu-ES',
        androidCode: 'eu-rES',
        osxCode: 'eu.lproj',
        osxLocale: 'eu',
    },
    {
        name: 'Belarusian',
        twoLettersCode: 'be',
        threeLettersCode: 'bel',
        locale: 'be-BY',
        androidCode: 'be-rBY',
        osxCode: 'be.lproj',
        osxLocale: 'be',
    },
    {
        name: 'Bengali',
        twoLettersCode: 'bn',
        threeLettersCode: 'ben',
        locale: 'bn-BD',
        androidCode: 'bn-rBD',
        osxCode: 'bn.lproj',
        osxLocale: 'bn',
    },
    {
        name: 'Bengali, India',
        twoLettersCode: 'bn',
        threeLettersCode: 'ben',
        locale: 'bn-IN',
        androidCode: 'bn-rIN',
        osxCode: 'bn-IN.lproj',
        osxLocale: 'bn_IN',
    },
    {
        name: 'Berber',
        twoLettersCode: 'ber',
        threeLettersCode: 'ber',
        locale: 'ber-DZ',
        androidCode: 'ber-rDZ',
        osxCode: 'ber.lproj',
        osxLocale: 'ber',
    },
    {
        name: 'Bihari',
        twoLettersCode: 'bh',
        threeLettersCode: 'bih',
        locale: 'bh-IN',
        androidCode: 'bh-rIN',
        osxCode: 'bh.lproj',
        osxLocale: 'bh',
    },
    {
        name: 'Birifor',
        twoLettersCode: 'bfo',
        threeLettersCode: 'bfo',
        locale: 'bfo-BF',
        androidCode: 'bfo-rBF',
        osxCode: 'bfo.lproj',
        osxLocale: 'bfo',
    },
    {
        name: 'Bislama',
        twoLettersCode: 'bi',
        threeLettersCode: 'bis',
        locale: 'bi-VU',
        androidCode: 'bi-rVU',
        osxCode: 'bi.lproj',
        osxLocale: 'bi',
    },
    {
        name: 'Bosnian',
        twoLettersCode: 'bs',
        threeLettersCode: 'bos',
        locale: 'bs-BA',
        androidCode: 'bs-rBA',
        osxCode: 'bs.lproj',
        osxLocale: 'bs',
    },
    {
        name: 'Breton',
        twoLettersCode: 'br',
        threeLettersCode: 'bre',
        locale: 'br-FR',
        androidCode: 'br-rFR',
        osxCode: 'br.lproj',
        osxLocale: 'br',
    },
    {
        name: 'Bulgarian',
        twoLettersCode: 'bg',
        threeLettersCode: 'bul',
        locale: 'bg-BG',
        androidCode: 'bg-rBG',
        osxCode: 'bg.lproj',
        osxLocale: 'bg',
    },
    {
        name: 'Burmese',
        twoLettersCode: 'my',
        threeLettersCode: 'mya',
        locale: 'my-MM',
        androidCode: 'my-rMM',
        osxCode: 'my.lproj',
        osxLocale: 'my',
    },
    {
        name: 'Catalan',
        twoLettersCode: 'ca',
        threeLettersCode: 'cat',
        locale: 'ca-ES',
        androidCode: 'ca-rES',
        osxCode: 'ca.lproj',
        osxLocale: 'ca',
    },
    {
        name: 'Cebuano',
        twoLettersCode: 'ceb',
        threeLettersCode: 'ceb',
        locale: 'ceb-PH',
        androidCode: 'ceb-rPH',
        osxCode: 'ceb.lproj',
        osxLocale: 'ceb',
    },
    {
        name: 'Chamorro',
        twoLettersCode: 'ch',
        threeLettersCode: 'cha',
        locale: 'ch-GU',
        androidCode: 'ch-rGU',
        osxCode: 'ch.lproj',
        osxLocale: 'ch',
    },
    {
        name: 'Chechen',
        twoLettersCode: 'ce',
        threeLettersCode: 'che',
        locale: 'ce-CE',
        androidCode: 'ce-rCE',
        osxCode: 'ce.lproj',
        osxLocale: 'ce',
    },
    {
        name: 'Cherokee',
        twoLettersCode: 'chr',
        threeLettersCode: 'chr',
        locale: 'chr-US',
        androidCode: 'chr-rUS',
        osxCode: 'chr.lproj',
        osxLocale: 'chr',
    },
    {
        name: 'Chewa',
        twoLettersCode: 'ny',
        threeLettersCode: 'nya',
        locale: 'ny-MW',
        androidCode: 'ny-rMW',
        osxCode: 'ny.lproj',
        osxLocale: 'ny',
    },
    {
        name: 'Chinese Simplified',
        twoLettersCode: 'zh',
        threeLettersCode: 'zho',
        locale: 'zh-CN',
        androidCode: 'zh-rCN',
        osxCode: 'zh-Hans.lproj',
        osxLocale: 'zh-Hans',
    },
    {
        name: 'Chinese Traditional',
        twoLettersCode: 'zh',
        threeLettersCode: 'zho',
        locale: 'zh-TW',
        androidCode: 'zh-rTW',
        osxCode: 'zh-Hant.lproj',
        osxLocale: 'zh-Hant',
    },
    {
        name: 'Chinese Traditional, Hong Kong',
        twoLettersCode: 'zh',
        threeLettersCode: 'zho',
        locale: 'zh-HK',
        androidCode: 'zh-rHK',
        osxCode: 'zh-HK.lproj',
        osxLocale: 'zh_HK',
    },
    {
        name: 'Chinese Traditional, Macau',
        twoLettersCode: 'zh',
        threeLettersCode: 'zho',
        locale: 'zh-MO',
        androidCode: 'zh-rMO',
        osxCode: 'zh-MO.lproj',
        osxLocale: 'zh_MO',
    },
    {
        name: 'Chinese Traditional, Singapore',
        twoLettersCode: 'zh',
        threeLettersCode: 'zho',
        locale: 'zh-SG',
        androidCode: 'zh-rSG',
        osxCode: 'zh-SG.lproj',
        osxLocale: 'zh_SG',
    },
    {
        name: 'Chuvash',
        twoLettersCode: 'cv',
        threeLettersCode: 'chv',
        locale: 'cv-CU',
        androidCode: 'cv-rCU',
        osxCode: 'cv.lproj',
        osxLocale: 'cv',
    },
    {
        name: 'Cornish',
        twoLettersCode: 'kw',
        threeLettersCode: 'cor',
        locale: 'kw-GB',
        androidCode: 'kw-rGB',
        osxCode: 'kw.lproj',
        osxLocale: 'kw',
    },
    {
        name: 'Corsican',
        twoLettersCode: 'co',
        threeLettersCode: 'cos',
        locale: 'co-FR',
        androidCode: 'co-rFR',
        osxCode: 'co.lproj',
        osxLocale: 'co',
    },
    {
        name: 'Cree',
        twoLettersCode: 'cr',
        threeLettersCode: 'cre',
        locale: 'cr-NT',
        androidCode: 'cr-rNT',
        osxCode: 'cr.lproj',
        osxLocale: 'cr',
    },
    {
        name: 'Croatian',
        twoLettersCode: 'hr',
        threeLettersCode: 'hrv',
        locale: 'hr-HR',
        androidCode: 'hr-rHR',
        osxCode: 'hr.lproj',
        osxLocale: 'hr',
    },
    {
        name: 'Czech',
        twoLettersCode: 'cs',
        threeLettersCode: 'ces',
        locale: 'cs-CZ',
        androidCode: 'cs-rCZ',
        osxCode: 'cs.lproj',
        osxLocale: 'cs',
    },
    {
        name: 'Danish',
        twoLettersCode: 'da',
        threeLettersCode: 'dan',
        locale: 'da-DK',
        androidCode: 'da-rDK',
        osxCode: 'da.lproj',
        osxLocale: 'da',
    },
    {
        name: 'Dari',
        twoLettersCode: 'fa',
        threeLettersCode: 'prs',
        locale: 'fa-AF',
        androidCode: 'fa-rAF',
        osxCode: 'fa-AF.lproj',
        osxLocale: 'fa_AF',
    },
    {
        name: 'Dhivehi',
        twoLettersCode: 'dv',
        threeLettersCode: 'div',
        locale: 'dv-MV',
        androidCode: 'dv-rMV',
        osxCode: 'dv.lproj',
        osxLocale: 'dv',
    },
    {
        name: 'Dutch',
        twoLettersCode: 'nl',
        threeLettersCode: 'nld',
        locale: 'nl-NL',
        androidCode: 'nl-rNL',
        osxCode: 'nl.lproj',
        osxLocale: 'nl',
    },
    {
        name: 'Dutch, Belgium',
        twoLettersCode: 'nl',
        threeLettersCode: 'nld',
        locale: 'nl-BE',
        androidCode: 'nl-rBE',
        osxCode: 'nl-BE.lproj',
        osxLocale: 'nl_BE',
    },
    {
        name: 'Dutch, Suriname',
        twoLettersCode: 'nl',
        threeLettersCode: 'nld',
        locale: 'nl-SR',
        androidCode: 'nl-rSR',
        osxCode: 'nl-SR.lproj',
        osxLocale: 'nl_SR',
    },
    {
        name: 'Dzongkha',
        twoLettersCode: 'dz',
        threeLettersCode: 'dzo',
        locale: 'dz-BT',
        androidCode: 'dz-rBT',
        osxCode: 'dz.lproj',
        osxLocale: 'dz',
    },
    {
        name: 'English',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-US',
        androidCode: 'en-rUS',
        osxCode: 'en.lproj',
        osxLocale: 'en',
    },
    {
        name: 'English, Arabia',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-AR',
        androidCode: 'en-rAR',
        osxCode: 'en-AR.lproj',
        osxLocale: 'en_AR',
    },
    {
        name: 'English, Australia',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-AU',
        androidCode: 'en-rAU',
        osxCode: 'en-AU.lproj',
        osxLocale: 'en_AU',
    },
    {
        name: 'English, Belize',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-BZ',
        androidCode: 'en-rBZ',
        osxCode: 'en-BZ.lproj',
        osxLocale: 'en_BZ',
    },
    {
        name: 'English, Canada',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-CA',
        androidCode: 'en-rCA',
        osxCode: 'en-CA.lproj',
        osxLocale: 'en_CA',
    },
    {
        name: 'English, Caribbean',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-CB',
        androidCode: 'en-rCB',
        osxCode: 'en-CB.lproj',
        osxLocale: 'en_CB',
    },
    {
        name: 'English, China',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-CN',
        androidCode: 'en-rCN',
        osxCode: 'en-CN.lproj',
        osxLocale: 'en_CN',
    },
    {
        name: 'English, Denmark',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-DK',
        androidCode: 'en-rDK',
        osxCode: 'en-DK.lproj',
        osxLocale: 'en_DK',
    },
    {
        name: 'English, Hong Kong',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-HK',
        androidCode: 'en-rHK',
        osxCode: 'en-HK.lproj',
        osxLocale: 'en_HK',
    },
    {
        name: 'English, India',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-IN',
        androidCode: 'en-rIN',
        osxCode: 'en-IN.lproj',
        osxLocale: 'en_IN',
    },
    {
        name: 'English, Indonesia',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-ID',
        androidCode: 'en-rID',
        osxCode: 'en-ID.lproj',
        osxLocale: 'en_ID',
    },
    {
        name: 'English, Ireland',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-IE',
        androidCode: 'en-rIE',
        osxCode: 'en-IE.lproj',
        osxLocale: 'en_IE',
    },
    {
        name: 'English, Jamaica',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-JM',
        androidCode: 'en-rJM',
        osxCode: 'en-JM.lproj',
        osxLocale: 'en_JM',
    },
    {
        name: 'English, Japan',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-JA',
        androidCode: 'en-rJA',
        osxCode: 'en-JA.lproj',
        osxLocale: 'en_JA',
    },
    {
        name: 'English, Malaysia',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-MY',
        androidCode: 'en-rMY',
        osxCode: 'en-MY.lproj',
        osxLocale: 'en_MY',
    },
    {
        name: 'English, New Zealand',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-NZ',
        androidCode: 'en-rNZ',
        osxCode: 'en-NZ.lproj',
        osxLocale: 'en_NZ',
    },
    {
        name: 'English, Norway',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-NO',
        androidCode: 'en-rNO',
        osxCode: 'en-NO.lproj',
        osxLocale: 'en_NO',
    },
    {
        name: 'English, Philippines',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-PH',
        androidCode: 'en-rPH',
        osxCode: 'en-PH.lproj',
        osxLocale: 'en_PH',
    },
    {
        name: 'English, Puerto Rico',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-PR',
        androidCode: 'en-rPR',
        osxCode: 'en-PR.lproj',
        osxLocale: 'en_PR',
    },
    {
        name: 'English, Singapore',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-SG',
        androidCode: 'en-rSG',
        osxCode: 'en-SG.lproj',
        osxLocale: 'en_SG',
    },
    {
        name: 'English, South Africa',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-ZA',
        androidCode: 'en-rZA',
        osxCode: 'en-ZA.lproj',
        osxLocale: 'en_ZA',
    },
    {
        name: 'English, Sweden',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-SE',
        androidCode: 'en-rSE',
        osxCode: 'en-SE.lproj',
        osxLocale: 'en_SE',
    },
    {
        name: 'English, United Kingdom',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-GB',
        androidCode: 'en-rGB',
        osxCode: 'en-GB.lproj',
        osxLocale: 'en_GB',
    },
    {
        name: 'English, United States',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-US',
        androidCode: 'en-rUS',
        osxCode: 'en-US.lproj',
        osxLocale: 'en_US',
    },
    {
        name: 'English, Zimbabwe',
        twoLettersCode: 'en',
        threeLettersCode: 'eng',
        locale: 'en-ZW',
        androidCode: 'en-rZW',
        osxCode: 'en-ZW.lproj',
        osxLocale: 'en_ZW',
    },
    {
        name: 'Esperanto',
        twoLettersCode: 'eo',
        threeLettersCode: 'epo',
        locale: 'eo-UY',
        androidCode: 'eo-rUY',
        osxCode: 'eo.lproj',
        osxLocale: 'eo',
    },
    {
        name: 'Estonian',
        twoLettersCode: 'et',
        threeLettersCode: 'est',
        locale: 'et-EE',
        androidCode: 'et-rEE',
        osxCode: 'et.lproj',
        osxLocale: 'et',
    },
    {
        name: 'Ewe',
        twoLettersCode: 'ee',
        threeLettersCode: 'ewe',
        locale: 'ee-GH',
        androidCode: 'ee-rGH',
        osxCode: 'ee.lproj',
        osxLocale: 'ee',
    },
    {
        name: 'Faroese',
        twoLettersCode: 'fo',
        threeLettersCode: 'fao',
        locale: 'fo-FO',
        androidCode: 'fo-rFO',
        osxCode: 'fo.lproj',
        osxLocale: 'fo',
    },
    {
        name: 'Fijian',
        twoLettersCode: 'fj',
        threeLettersCode: 'fij',
        locale: 'fj-FJ',
        androidCode: 'fj-rFJ',
        osxCode: 'fj.lproj',
        osxLocale: 'fj',
    },
    {
        name: 'Filipino',
        twoLettersCode: 'fil',
        threeLettersCode: 'fil',
        locale: 'fil-PH',
        androidCode: 'fil-rPH',
        osxCode: 'fil.lproj',
        osxLocale: 'fil',
    },
    {
        name: 'Finnish',
        twoLettersCode: 'fi',
        threeLettersCode: 'fin',
        locale: 'fi-FI',
        androidCode: 'fi-rFI',
        osxCode: 'fi.lproj',
        osxLocale: 'fi',
    },
    {
        name: 'Flemish',
        twoLettersCode: 'vls',
        threeLettersCode: 'vls',
        locale: 'vls-BE',
        androidCode: 'vls-rBE',
        osxCode: 'vls.lproj',
        osxLocale: 'vls',
    },
    {
        name: 'Franconian',
        twoLettersCode: 'fra',
        threeLettersCode: 'gem',
        locale: 'fra-DE',
        androidCode: 'fra-rDE',
        osxCode: 'fra.lproj',
        osxLocale: 'fra',
    },
    {
        name: 'French',
        twoLettersCode: 'fr',
        threeLettersCode: 'fra',
        locale: 'fr-FR',
        androidCode: 'fr-rFR',
        osxCode: 'fr.lproj',
        osxLocale: 'fr',
    },
    {
        name: 'French, Belgium',
        twoLettersCode: 'fr',
        threeLettersCode: 'fra',
        locale: 'fr-BE',
        androidCode: 'fr-rBE',
        osxCode: 'fr-BE.lproj',
        osxLocale: 'fr_BE',
    },
    {
        name: 'French, Canada',
        twoLettersCode: 'fr',
        threeLettersCode: 'fra',
        locale: 'fr-CA',
        androidCode: 'fr-rCA',
        osxCode: 'fr-CA.lproj',
        osxLocale: 'fr_CA',
    },
    {
        name: 'French, Luxembourg',
        twoLettersCode: 'fr',
        threeLettersCode: 'fra',
        locale: 'fr-LU',
        androidCode: 'fr-rLU',
        osxCode: 'fr-LU.lproj',
        osxLocale: 'fr_LU',
    },
    {
        name: 'French, Quebec',
        twoLettersCode: 'fr',
        threeLettersCode: 'fra',
        locale: 'fr-QC',
        androidCode: 'fr-rQC',
        osxCode: 'fr-QC.lproj',
        osxLocale: 'fr_QC',
    },
    {
        name: 'French, Switzerland',
        twoLettersCode: 'fr',
        threeLettersCode: 'fra',
        locale: 'fr-CH',
        androidCode: 'fr-rCH',
        osxCode: 'fr-CH.lproj',
        osxLocale: 'fr_CH',
    },
    {
        name: 'Frisian',
        twoLettersCode: 'fy',
        threeLettersCode: 'fry',
        locale: 'fy-NL',
        androidCode: 'fy-rNL',
        osxCode: 'fy.lproj',
        osxLocale: 'fy',
    },
    {
        name: 'Friulian',
        twoLettersCode: 'fur',
        threeLettersCode: 'fur',
        locale: 'fur-IT',
        androidCode: 'fur-rIT',
        osxCode: 'fur.lproj',
        osxLocale: 'fur',
    },
    {
        name: 'Fula',
        twoLettersCode: 'ff',
        threeLettersCode: 'ful',
        locale: 'ff-ZA',
        androidCode: 'ff-rZA',
        osxCode: 'ff.lproj',
        osxLocale: 'ff',
    },
    {
        name: 'Ga',
        twoLettersCode: 'gaa',
        threeLettersCode: 'gaa',
        locale: 'gaa-GH',
        androidCode: 'gaa-rGH',
        osxCode: 'gaa.lproj',
        osxLocale: 'gaa',
    },
    {
        name: 'Galician',
        twoLettersCode: 'gl',
        threeLettersCode: 'glg',
        locale: 'gl-ES',
        androidCode: 'gl-rES',
        osxCode: 'gl.lproj',
        osxLocale: 'gl',
    },
    {
        name: 'Georgian',
        twoLettersCode: 'ka',
        threeLettersCode: 'kat',
        locale: 'ka-GE',
        androidCode: 'ka-rGE',
        osxCode: 'ka.lproj',
        osxLocale: 'ka',
    },
    {
        name: 'German',
        twoLettersCode: 'de',
        threeLettersCode: 'deu',
        locale: 'de-DE',
        androidCode: 'de-rDE',
        osxCode: 'de.lproj',
        osxLocale: 'de',
    },
    {
        name: 'German, Austria',
        twoLettersCode: 'de',
        threeLettersCode: 'deu',
        locale: 'de-AT',
        androidCode: 'de-rAT',
        osxCode: 'de-AT.lproj',
        osxLocale: 'de_AT',
    },
    {
        name: 'German, Belgium',
        twoLettersCode: 'de',
        threeLettersCode: 'deu',
        locale: 'de-BE',
        androidCode: 'de-rBE',
        osxCode: 'de-BE.lproj',
        osxLocale: 'de_BE',
    },
    {
        name: 'German, Liechtenstein',
        twoLettersCode: 'de',
        threeLettersCode: 'deu',
        locale: 'de-LI',
        androidCode: 'de-rLI',
        osxCode: 'de-LI.lproj',
        osxLocale: 'de_LI',
    },
    {
        name: 'German, Luxembourg',
        twoLettersCode: 'de',
        threeLettersCode: 'deu',
        locale: 'de-LU',
        androidCode: 'de-rLU',
        osxCode: 'de-LU.lproj',
        osxLocale: 'de_LU',
    },
    {
        name: 'German, Switzerland',
        twoLettersCode: 'de',
        threeLettersCode: 'deu',
        locale: 'de-CH',
        androidCode: 'de-rCH',
        osxCode: 'de-CH.lproj',
        osxLocale: 'de_CH',
    },
    {
        name: 'Greek',
        twoLettersCode: 'el',
        threeLettersCode: 'ell',
        locale: 'el-GR',
        androidCode: 'el-rGR',
        osxCode: 'el.lproj',
        osxLocale: 'el',
    },
    {
        name: 'Greek, Cyprus',
        twoLettersCode: 'el',
        threeLettersCode: 'ell',
        locale: 'el-CY',
        androidCode: 'el-rCY',
        osxCode: 'el-CY.lproj',
        osxLocale: 'el_CY',
    },
    {
        name: 'Greenlandic',
        twoLettersCode: 'kl',
        threeLettersCode: 'kal',
        locale: 'kl-GL',
        androidCode: 'kl-rGL',
        osxCode: 'kl.lproj',
        osxLocale: 'kl',
    },
    {
        name: 'Guarani',
        twoLettersCode: 'gn',
        threeLettersCode: 'grn',
        locale: 'gn-PY',
        androidCode: 'gn-rPY',
        osxCode: 'gn.lproj',
        osxLocale: 'gn',
    },
    {
        name: 'Gujarati',
        twoLettersCode: 'gu',
        threeLettersCode: 'guj',
        locale: 'gu-IN',
        androidCode: 'gu-rIN',
        osxCode: 'gu.lproj',
        osxLocale: 'gu',
    },
    {
        name: 'Haitian Creole',
        twoLettersCode: 'ht',
        threeLettersCode: 'hat',
        locale: 'ht-HT',
        androidCode: 'ht-rHT',
        osxCode: 'ht.lproj',
        osxLocale: 'ht',
    },
    {
        name: 'Hausa',
        twoLettersCode: 'ha',
        threeLettersCode: 'hau',
        locale: 'ha-HG',
        androidCode: 'ha-rHG',
        osxCode: 'ha.lproj',
        osxLocale: 'ha',
    },
    {
        name: 'Hawaiian',
        twoLettersCode: 'haw',
        threeLettersCode: 'haw',
        locale: 'haw-US',
        androidCode: 'haw-rUS',
        osxCode: 'haw.lproj',
        osxLocale: 'haw',
    },
    {
        name: 'Hebrew',
        twoLettersCode: 'he',
        threeLettersCode: 'heb',
        locale: 'he-IL',
        androidCode: 'iw-rIL',
        osxCode: 'he.lproj',
        osxLocale: 'he',
    },
    {
        name: 'Herero',
        twoLettersCode: 'hz',
        threeLettersCode: 'her',
        locale: 'hz-NA',
        androidCode: 'hz-rNA',
        osxCode: 'hz.lproj',
        osxLocale: 'hz',
    },
    {
        name: 'Hiligaynon',
        twoLettersCode: 'hil',
        threeLettersCode: 'hil',
        locale: 'hil-PH',
        androidCode: 'hil-rPH',
        osxCode: 'hil.lproj',
        osxLocale: 'hil',
    },
    {
        name: 'Hindi',
        twoLettersCode: 'hi',
        threeLettersCode: 'hin',
        locale: 'hi-IN',
        androidCode: 'hi-rIN',
        osxCode: 'hi.lproj',
        osxLocale: 'hi',
    },
    {
        name: 'Hiri Motu',
        twoLettersCode: 'ho',
        threeLettersCode: 'hmo',
        locale: 'ho-PG',
        androidCode: 'ho-rPG',
        osxCode: 'ho.lproj',
        osxLocale: 'ho',
    },
    {
        name: 'Hmong',
        twoLettersCode: 'hmn',
        threeLettersCode: 'hmn',
        locale: 'hmn-CN',
        androidCode: 'hmn-rCN',
        osxCode: 'hmn.lproj',
        osxLocale: 'hmn',
    },
    {
        name: 'Hungarian',
        twoLettersCode: 'hu',
        threeLettersCode: 'hun',
        locale: 'hu-HU',
        androidCode: 'hu-rHU',
        osxCode: 'hu.lproj',
        osxLocale: 'hu',
    },
    {
        name: 'Icelandic',
        twoLettersCode: 'is',
        threeLettersCode: 'isl',
        locale: 'is-IS',
        androidCode: 'is-rIS',
        osxCode: 'is.lproj',
        osxLocale: 'is',
    },
    {
        name: 'Ido',
        twoLettersCode: 'io',
        threeLettersCode: 'ido',
        locale: 'io-EN',
        androidCode: 'io-rEN',
        osxCode: 'ido.lproj',
        osxLocale: 'ido',
    },
    {
        name: 'Igbo',
        twoLettersCode: 'ig',
        threeLettersCode: 'ibo',
        locale: 'ig-NG',
        androidCode: 'ig-rNG',
        osxCode: 'ig.lproj',
        osxLocale: 'ig',
    },
    {
        name: 'Ilokano',
        twoLettersCode: 'ilo',
        threeLettersCode: 'ilo',
        locale: 'ilo-PH',
        androidCode: 'ilo-rPH',
        osxCode: 'ilo.lproj',
        osxLocale: 'ilo',
    },
    {
        name: 'Indonesian',
        twoLettersCode: 'id',
        threeLettersCode: 'ind',
        locale: 'id-ID',
        androidCode: 'in-rID',
        osxCode: 'id.lproj',
        osxLocale: 'id',
    },
    {
        name: 'Inuktitut',
        twoLettersCode: 'iu',
        threeLettersCode: 'iku',
        locale: 'iu-NU',
        androidCode: 'iu-rNU',
        osxCode: 'iu.lproj',
        osxLocale: 'iu',
    },
    {
        name: 'Irish',
        twoLettersCode: 'ga',
        threeLettersCode: 'gle',
        locale: 'ga-IE',
        androidCode: 'ga-rIE',
        osxCode: 'ga.lproj',
        osxLocale: 'ga',
    },
    {
        name: 'Italian',
        twoLettersCode: 'it',
        threeLettersCode: 'ita',
        locale: 'it-IT',
        androidCode: 'it-rIT',
        osxCode: 'it.lproj',
        osxLocale: 'it',
    },
    {
        name: 'Italian, Switzerland',
        twoLettersCode: 'it',
        threeLettersCode: 'ita',
        locale: 'it-CH',
        androidCode: 'it-rCH',
        osxCode: 'it-CH.lproj',
        osxLocale: 'it_CH',
    },
    {
        name: 'Japanese',
        twoLettersCode: 'ja',
        threeLettersCode: 'jpn',
        locale: 'ja-JP',
        androidCode: 'ja-rJP',
        osxCode: 'ja.lproj',
        osxLocale: 'ja',
    },
    {
        name: 'Javanese',
        twoLettersCode: 'jv',
        threeLettersCode: 'jav',
        locale: 'jv-ID',
        androidCode: 'jv-rID',
        osxCode: 'jv.lproj',
        osxLocale: 'jv',
    },
    {
        name: "K'iche'",
        twoLettersCode: 'quc',
        threeLettersCode: 'quc',
        locale: 'quc-GT',
        androidCode: 'quc-rGT',
        osxCode: 'quc.lproj',
        osxLocale: 'quc',
    },
    {
        name: 'Kabyle',
        twoLettersCode: 'kab',
        threeLettersCode: 'kab',
        locale: 'kab-KAB',
        androidCode: 'kab-rKAB',
        osxCode: 'kab.lproj',
        osxLocale: 'kab',
    },
    {
        name: 'Kannada',
        twoLettersCode: 'kn',
        threeLettersCode: 'kan',
        locale: 'kn-IN',
        androidCode: 'kn-rIN',
        osxCode: 'kn.lproj',
        osxLocale: 'kn',
    },
    {
        name: 'Kapampangan',
        twoLettersCode: 'pam',
        threeLettersCode: 'pam',
        locale: 'pam-PH',
        androidCode: 'pam-rPH',
        osxCode: 'pam.lproj',
        osxLocale: 'pam',
    },
    {
        name: 'Kashmiri',
        twoLettersCode: 'ks',
        threeLettersCode: 'kas',
        locale: 'ks-IN',
        androidCode: 'ks-rIN',
        osxCode: 'ks.lproj',
        osxLocale: 'ks',
    },
    {
        name: 'Kashmiri, Pakistan',
        twoLettersCode: 'ks',
        threeLettersCode: 'kas',
        locale: 'ks-PK',
        androidCode: 'ks-rPK',
        osxCode: 'ks-PK.lproj',
        osxLocale: 'ks_PK',
    },
    {
        name: 'Kashubian',
        twoLettersCode: 'csb',
        threeLettersCode: 'csb',
        locale: 'csb-PL',
        androidCode: 'csb-rPL',
        osxCode: 'csb.lproj',
        osxLocale: 'csb',
    },
    {
        name: 'Kazakh',
        twoLettersCode: 'kk',
        threeLettersCode: 'kaz',
        locale: 'kk-KZ',
        androidCode: 'kk-rKZ',
        osxCode: 'kk.lproj',
        osxLocale: 'kk',
    },
    {
        name: 'Khmer',
        twoLettersCode: 'km',
        threeLettersCode: 'khm',
        locale: 'km-KH',
        androidCode: 'km-rKH',
        osxCode: 'km.lproj',
        osxLocale: 'km',
    },
    {
        name: 'Kinyarwanda',
        twoLettersCode: 'rw',
        threeLettersCode: 'kin',
        locale: 'rw-RW',
        androidCode: 'rw-rRW',
        osxCode: 'rw.lproj',
        osxLocale: 'rw',
    },
    {
        name: 'Komi',
        twoLettersCode: 'kv',
        threeLettersCode: 'kom',
        locale: 'kv-KO',
        androidCode: 'kv-rKO',
        osxCode: 'kv.lproj',
        osxLocale: 'kv',
    },
    {
        name: 'Kongo',
        twoLettersCode: 'kg',
        threeLettersCode: 'kon',
        locale: 'kg-CG',
        androidCode: 'kg-rCG',
        osxCode: 'kg.lproj',
        osxLocale: 'kg',
    },
    {
        name: 'Konkani',
        twoLettersCode: 'kok',
        threeLettersCode: 'kok',
        locale: 'kok-IN',
        androidCode: 'kok-rIN',
        osxCode: 'kok.lproj',
        osxLocale: 'kok',
    },
    {
        name: 'Korean',
        twoLettersCode: 'ko',
        threeLettersCode: 'kor',
        locale: 'ko-KR',
        androidCode: 'ko-rKR',
        osxCode: 'ko.lproj',
        osxLocale: 'ko',
    },
    {
        name: 'Kurdish',
        twoLettersCode: 'ku',
        threeLettersCode: 'kur',
        locale: 'ku-TR',
        androidCode: 'ku-rTR',
        osxCode: 'ku.lproj',
        osxLocale: 'ku',
    },
    {
        name: 'Kurmanji (Kurdish)',
        twoLettersCode: 'ku',
        threeLettersCode: 'kmr',
        locale: 'kmr-TR',
        androidCode: 'kmr-rTR',
        osxCode: 'kmr.lproj',
        osxLocale: 'kmr',
    },
    {
        name: 'Kwanyama',
        twoLettersCode: 'kj',
        threeLettersCode: 'kua',
        locale: 'kj-AO',
        androidCode: 'kj-rAO',
        osxCode: 'kj.lproj',
        osxLocale: 'kj',
    },
    {
        name: 'Kyrgyz',
        twoLettersCode: 'ky',
        threeLettersCode: 'kir',
        locale: 'ky-KG',
        androidCode: 'ky-rKG',
        osxCode: 'ky.lproj',
        osxLocale: 'ky',
    },
    {
        name: 'Lao',
        twoLettersCode: 'lo',
        threeLettersCode: 'lao',
        locale: 'lo-LA',
        androidCode: 'lo-rLA',
        osxCode: 'lo.lproj',
        osxLocale: 'lo',
    },
    {
        name: 'Latin',
        twoLettersCode: 'la',
        threeLettersCode: 'lat',
        locale: 'la-LA',
        androidCode: 'la-rLA',
        osxCode: 'la.lproj',
        osxLocale: 'la',
    },
    {
        name: 'Latvian',
        twoLettersCode: 'lv',
        threeLettersCode: 'lav',
        locale: 'lv-LV',
        androidCode: 'lv-rLV',
        osxCode: 'lv.lproj',
        osxLocale: 'lv',
    },
    {
        name: 'Ligurian',
        twoLettersCode: 'lij',
        threeLettersCode: 'lij',
        locale: 'lij-IT',
        androidCode: 'lij-rIT',
        osxCode: 'lij.lproj',
        osxLocale: 'lij',
    },
    {
        name: 'Limburgish',
        twoLettersCode: 'li',
        threeLettersCode: 'lim',
        locale: 'li-LI',
        androidCode: 'li-rLI',
        osxCode: 'li.lproj',
        osxLocale: 'li',
    },
    {
        name: 'Lingala',
        twoLettersCode: 'ln',
        threeLettersCode: 'lin',
        locale: 'ln-CD',
        androidCode: 'ln-rCD',
        osxCode: 'ln.lproj',
        osxLocale: 'ln',
    },
    {
        name: 'Lithuanian',
        twoLettersCode: 'lt',
        threeLettersCode: 'lit',
        locale: 'lt-LT',
        androidCode: 'lt-rLT',
        osxCode: 'lt.lproj',
        osxLocale: 'lt',
    },
    {
        name: 'Low German',
        twoLettersCode: 'nds',
        threeLettersCode: 'nds',
        locale: 'nds-DE',
        androidCode: 'nds-rDE',
        osxCode: 'nds.lproj',
        osxLocale: 'nds',
    },
    {
        name: 'Lower Sorbian',
        twoLettersCode: 'dsb',
        threeLettersCode: 'dsb',
        locale: 'dsb-DE',
        androidCode: 'dsb-rDE',
        osxCode: 'dsb.lproj',
        osxLocale: 'dsb',
    },
    {
        name: 'Luganda',
        twoLettersCode: 'lg',
        threeLettersCode: 'lug',
        locale: 'lg-UG',
        androidCode: 'lg-rUG',
        osxCode: 'lg.lproj',
        osxLocale: 'lg',
    },
    {
        name: 'Luhya',
        twoLettersCode: 'luy',
        threeLettersCode: 'luy',
        locale: 'luy-KE',
        androidCode: 'luy-rKE',
        osxCode: 'luy.lproj',
        osxLocale: 'luy',
    },
    {
        name: 'Luxembourgish',
        twoLettersCode: 'lb',
        threeLettersCode: 'ltz',
        locale: 'lb-LU',
        androidCode: 'lb-rLU',
        osxCode: 'lb.lproj',
        osxLocale: 'lb',
    },
    {
        name: 'Macedonian',
        twoLettersCode: 'mk',
        threeLettersCode: 'mkd',
        locale: 'mk-MK',
        androidCode: 'mk-rMK',
        osxCode: 'mk.lproj',
        osxLocale: 'mk',
    },
    {
        name: 'Maithili',
        twoLettersCode: 'mai',
        threeLettersCode: 'mai',
        locale: 'mai-IN',
        androidCode: 'mai-rIN',
        osxCode: 'mai.lproj',
        osxLocale: 'mai',
    },
    {
        name: 'Malagasy',
        twoLettersCode: 'mg',
        threeLettersCode: 'mlg',
        locale: 'mg-MG',
        androidCode: 'mg-rMG',
        osxCode: 'mg.lproj',
        osxLocale: 'mg',
    },
    {
        name: 'Malay',
        twoLettersCode: 'ms',
        threeLettersCode: 'msa',
        locale: 'ms-MY',
        androidCode: 'ms-rMY',
        osxCode: 'ms.lproj',
        osxLocale: 'ms',
    },
    {
        name: 'Malay, Brunei',
        twoLettersCode: 'ms',
        threeLettersCode: 'msa',
        locale: 'ms-BN',
        androidCode: 'ms-rBN',
        osxCode: 'ms-BN.lproj',
        osxLocale: 'ms_BN',
    },
    {
        name: 'Malayalam',
        twoLettersCode: 'ml',
        threeLettersCode: 'mal',
        locale: 'ml-IN',
        androidCode: 'ml-rIN',
        osxCode: 'ml.lproj',
        osxLocale: 'ml',
    },
    {
        name: 'Maltese',
        twoLettersCode: 'mt',
        threeLettersCode: 'mlt',
        locale: 'mt-MT',
        androidCode: 'mt-rMT',
        osxCode: 'mt.lproj',
        osxLocale: 'mt',
    },
    {
        name: 'Maori',
        twoLettersCode: 'mi',
        threeLettersCode: 'mri',
        locale: 'mi-NZ',
        androidCode: 'mi-rNZ',
        osxCode: 'mi.lproj',
        osxLocale: 'mi',
    },
    {
        name: 'Mapudungun',
        twoLettersCode: 'arn',
        threeLettersCode: 'arn',
        locale: 'arn-CL',
        androidCode: 'arn-rCL',
        osxCode: 'arn.lproj',
        osxLocale: 'arn',
    },
    {
        name: 'Marathi',
        twoLettersCode: 'mr',
        threeLettersCode: 'mar',
        locale: 'mr-IN',
        androidCode: 'mr-rIN',
        osxCode: 'mr.lproj',
        osxLocale: 'mr',
    },
    {
        name: 'Marshallese',
        twoLettersCode: 'mh',
        threeLettersCode: 'mah',
        locale: 'mh-MH',
        androidCode: 'mh-rMH',
        osxCode: 'mh.lproj',
        osxLocale: 'mh',
    },
    {
        name: 'Mongolian',
        twoLettersCode: 'mn',
        threeLettersCode: 'mon',
        locale: 'mn-MN',
        androidCode: 'mn-rMN',
        osxCode: 'mn.lproj',
        osxLocale: 'mn',
    },
    {
        name: 'Mossi',
        twoLettersCode: 'mos',
        threeLettersCode: 'mos',
        locale: 'mos-MOS',
        androidCode: 'mos-rMOS',
        osxCode: 'mos.lproj',
        osxLocale: 'mos',
    },
    {
        name: 'Nauru',
        twoLettersCode: 'na',
        threeLettersCode: 'nau',
        locale: 'na-NR',
        androidCode: 'na-rNR',
        osxCode: 'na.lproj',
        osxLocale: 'na',
    },
    {
        name: 'Ndonga',
        twoLettersCode: 'ng',
        threeLettersCode: 'ndo',
        locale: 'ng-NA',
        androidCode: 'ng-rNA',
        osxCode: 'ng.lproj',
        osxLocale: 'ng',
    },
    {
        name: 'Nepali',
        twoLettersCode: 'ne',
        threeLettersCode: 'nep',
        locale: 'ne-NP',
        androidCode: 'ne-rNP',
        osxCode: 'ne.lproj',
        osxLocale: 'ne',
    },
    {
        name: 'Nepali, India',
        twoLettersCode: 'ne',
        threeLettersCode: 'nep',
        locale: 'ne-IN',
        androidCode: 'ne-rIN',
        osxCode: 'ne-IN.lproj',
        osxLocale: 'ne_IN',
    },
    {
        name: 'Nigerian Pidgin',
        twoLettersCode: 'pcm',
        threeLettersCode: 'pcm',
        locale: 'pcm-NG',
        androidCode: 'pcm-rNG',
        osxCode: 'pcm.lproj',
        osxLocale: 'pcm',
    },
    {
        name: 'Northern Sami',
        twoLettersCode: 'se',
        threeLettersCode: 'sme',
        locale: 'se-NO',
        androidCode: 'se-rNO',
        osxCode: 'se.lproj',
        osxLocale: 'se',
    },
    {
        name: 'Northern Sotho',
        twoLettersCode: 'nso',
        threeLettersCode: 'nso',
        locale: 'ns-ZA',
        androidCode: 'ns-rZA',
        osxCode: 'nso.lproj',
        osxLocale: 'nso',
    },
    {
        name: 'Norwegian',
        twoLettersCode: 'no',
        threeLettersCode: 'nor',
        locale: 'no-NO',
        androidCode: 'no-rNO',
        osxCode: 'no.lproj',
        osxLocale: 'no',
    },
    {
        name: 'Norwegian Bokmal',
        twoLettersCode: 'nb',
        threeLettersCode: 'nob',
        locale: 'nb-NO',
        androidCode: 'nb-rNO',
        osxCode: 'nb.lproj',
        osxLocale: 'nb',
    },
    {
        name: 'Norwegian Nynorsk',
        twoLettersCode: 'nn',
        threeLettersCode: 'nno',
        locale: 'nn-NO',
        androidCode: 'nn-rNO',
        osxCode: 'nn-NO.lproj',
        osxLocale: 'nn_NO',
    },
    {
        name: 'Occitan',
        twoLettersCode: 'oc',
        threeLettersCode: 'oci',
        locale: 'oc-FR',
        androidCode: 'oc-rFR',
        osxCode: 'oc.lproj',
        osxLocale: 'oc',
    },
    {
        name: 'Odia',
        twoLettersCode: 'or',
        threeLettersCode: 'ori',
        locale: 'or-IN',
        androidCode: 'or-rIN',
        osxCode: 'or.lproj',
        osxLocale: 'or',
    },
    {
        name: 'Ojibwe',
        twoLettersCode: 'oj',
        threeLettersCode: 'oji',
        locale: 'oj-CA',
        androidCode: 'oj-rCA',
        osxCode: 'oj.lproj',
        osxLocale: 'oj',
    },
    {
        name: 'Oromo',
        twoLettersCode: 'om',
        threeLettersCode: 'orm',
        locale: 'om-ET',
        androidCode: 'om-rET',
        osxCode: 'om.lproj',
        osxLocale: 'om',
    },
    {
        name: 'Ossetian',
        twoLettersCode: 'os',
        threeLettersCode: 'oss',
        locale: 'os-SE',
        androidCode: 'os-rSE',
        osxCode: 'os.lproj',
        osxLocale: 'os',
    },
    {
        name: 'Pali',
        twoLettersCode: 'pi',
        threeLettersCode: 'pli',
        locale: 'pi-IN',
        androidCode: 'pi-rIN',
        osxCode: 'pi.lproj',
        osxLocale: 'pi',
    },
    {
        name: 'Papiamento',
        twoLettersCode: 'pap',
        threeLettersCode: 'pap',
        locale: 'pap-PAP',
        androidCode: 'pap-rPAP',
        osxCode: 'pap.lproj',
        osxLocale: 'pap',
    },
    {
        name: 'Pashto',
        twoLettersCode: 'ps',
        threeLettersCode: 'pus',
        locale: 'ps-AF',
        androidCode: 'ps-rAF',
        osxCode: 'ps.lproj',
        osxLocale: 'ps',
    },
    {
        name: 'Persian',
        twoLettersCode: 'fa',
        threeLettersCode: 'fas',
        locale: 'fa-IR',
        androidCode: 'fa-rIR',
        osxCode: 'fa.lproj',
        osxLocale: 'fa',
    },
    {
        name: 'Polish',
        twoLettersCode: 'pl',
        threeLettersCode: 'pol',
        locale: 'pl-PL',
        androidCode: 'pl-rPL',
        osxCode: 'pl.lproj',
        osxLocale: 'pl',
    },
    {
        name: 'Portuguese',
        twoLettersCode: 'pt',
        threeLettersCode: 'por',
        locale: 'pt-PT',
        androidCode: 'pt-rPT',
        osxCode: 'pt.lproj',
        osxLocale: 'pt',
    },
    {
        name: 'Portuguese, Brazilian',
        twoLettersCode: 'pt',
        threeLettersCode: 'por',
        locale: 'pt-BR',
        androidCode: 'pt-rBR',
        osxCode: 'pt-BR.lproj',
        osxLocale: 'pt_BR',
    },
    {
        name: 'Punjabi',
        twoLettersCode: 'pa',
        threeLettersCode: 'pan',
        locale: 'pa-IN',
        androidCode: 'pa-rIN',
        osxCode: 'pa.lproj',
        osxLocale: 'pa',
    },
    {
        name: 'Punjabi, Pakistan',
        twoLettersCode: 'pa',
        threeLettersCode: 'pan',
        locale: 'pa-PK',
        androidCode: 'pa-rPK',
        osxCode: 'pa-PK.lproj',
        osxLocale: 'pa_PK',
    },
    {
        name: 'Quechua',
        twoLettersCode: 'qu',
        threeLettersCode: 'que',
        locale: 'qu-PE',
        androidCode: 'qu-rPE',
        osxCode: 'qu.lproj',
        osxLocale: 'qu',
    },
    {
        name: 'Romanian',
        twoLettersCode: 'ro',
        threeLettersCode: 'ron',
        locale: 'ro-RO',
        androidCode: 'ro-rRO',
        osxCode: 'ro.lproj',
        osxLocale: 'ro',
    },
    {
        name: 'Romansh',
        twoLettersCode: 'rm',
        threeLettersCode: 'roh',
        locale: 'rm-CH',
        androidCode: 'rm-rCH',
        osxCode: 'rm.lproj',
        osxLocale: 'rm',
    },
    {
        name: 'Rundi',
        twoLettersCode: 'rn',
        threeLettersCode: 'run',
        locale: 'rn-BI',
        androidCode: 'rn-rBI',
        osxCode: 'rn.lproj',
        osxLocale: 'rn',
    },
    {
        name: 'Russian',
        twoLettersCode: 'ru',
        threeLettersCode: 'rus',
        locale: 'ru-RU',
        androidCode: 'ru-rRU',
        osxCode: 'ru.lproj',
        osxLocale: 'ru',
    },
    {
        name: 'Russian, Belarus',
        twoLettersCode: 'ru',
        threeLettersCode: 'rus',
        locale: 'ru-BY',
        androidCode: 'ru-rBY',
        osxCode: 'ru-BY.lproj',
        osxLocale: 'ru_BY',
    },
    {
        name: 'Russian, Moldova',
        twoLettersCode: 'ru',
        threeLettersCode: 'rus',
        locale: 'ru-MD',
        androidCode: 'ru-rMD',
        osxCode: 'ru-MD.lproj',
        osxLocale: 'ru_MD',
    },
    {
        name: 'Sakha',
        twoLettersCode: 'sah',
        threeLettersCode: 'sah',
        locale: 'sah-SAH',
        androidCode: 'sah-rSAH',
        osxCode: 'sah.lproj',
        osxLocale: 'sah',
    },
    {
        name: 'Sango',
        twoLettersCode: 'sg',
        threeLettersCode: 'sag',
        locale: 'sg-CF',
        androidCode: 'sg-rCF',
        osxCode: 'sg.lproj',
        osxLocale: 'sg',
    },
    {
        name: 'Sanskrit',
        twoLettersCode: 'sa',
        threeLettersCode: 'san',
        locale: 'sa-IN',
        androidCode: 'sa-rIN',
        osxCode: 'sa.lproj',
        osxLocale: 'sa',
    },
    {
        name: 'Santali',
        twoLettersCode: 'sat',
        threeLettersCode: 'sat',
        locale: 'sat-IN',
        androidCode: 'sat-rIN',
        osxCode: 'sat.lproj',
        osxLocale: 'sat',
    },
    {
        name: 'Sardinian',
        twoLettersCode: 'sc',
        threeLettersCode: 'srd',
        locale: 'sc-IT',
        androidCode: 'sc-rIT',
        osxCode: 'sc.lproj',
        osxLocale: 'sc',
    },
    {
        name: 'Scots',
        twoLettersCode: 'sco',
        threeLettersCode: 'sco',
        locale: 'sco-GB',
        androidCode: 'sco-rGB',
        osxCode: 'sco.lproj',
        osxLocale: 'sco',
    },
    {
        name: 'Scottish Gaelic',
        twoLettersCode: 'gd',
        threeLettersCode: 'gla',
        locale: 'gd-GB',
        androidCode: 'gd-rGB',
        osxCode: 'gd.lproj',
        osxLocale: 'gd',
    },
    {
        name: 'Serbian',
        twoLettersCode: 'sr',
        threeLettersCode: 'srp',
        locale: 'srp',
        androidCode: 'srp',
        osxCode: 'sr.lproj',
        osxLocale: 'sr',
    },
    {
        name: 'Serbian (Cyrillic)',
        twoLettersCode: 'sr',
        threeLettersCode: 'srp',
        locale: 'sr-Cyrl',
        androidCode: 'sr-rCyrl',
        osxCode: 'sr-Cyrl.lproj',
        osxLocale: 'sr_Cyrl',
    },
    {
        name: 'Serbian (Latin)',
        twoLettersCode: 'sr',
        threeLettersCode: 'srp',
        locale: 'sr-Latn',
        androidCode: 'sr-rLatn',
        osxCode: 'sr-Latn.lproj',
        osxLocale: 'sr_Latn',
    },
    {
        name: 'Serbo-Croatian',
        twoLettersCode: 'sh',
        threeLettersCode: 'hbs',
        locale: 'sh-HR',
        androidCode: 'sh-rHR',
        osxCode: 'sh.lproj',
        osxLocale: 'sh',
    },
    {
        name: 'Seychellois Creole',
        twoLettersCode: 'crs',
        threeLettersCode: 'crs',
        locale: 'crs-SC',
        androidCode: 'crs-rSC',
        osxCode: 'crs.lproj',
        osxLocale: 'crs',
    },
    {
        name: 'Shona',
        twoLettersCode: 'sn',
        threeLettersCode: 'sna',
        locale: 'sn-ZW',
        androidCode: 'sn-rZW',
        osxCode: 'sn.lproj',
        osxLocale: 'sn',
    },
    {
        name: 'Sichuan Yi',
        twoLettersCode: 'ii',
        threeLettersCode: 'iii',
        locale: 'ii-CN',
        androidCode: 'ii-rCN',
        osxCode: 'ii.lproj',
        osxLocale: 'ii',
    },
    {
        name: 'Sindhi',
        twoLettersCode: 'sd',
        threeLettersCode: 'snd',
        locale: 'sd-PK',
        androidCode: 'sd-rPK',
        osxCode: 'sd.lproj',
        osxLocale: 'sd',
    },
    {
        name: 'Sinhala',
        twoLettersCode: 'si',
        threeLettersCode: 'sin',
        locale: 'si-LK',
        androidCode: 'si-rLK',
        osxCode: 'si.lproj',
        osxLocale: 'si',
    },
    {
        name: 'Slovak',
        twoLettersCode: 'sk',
        threeLettersCode: 'slk',
        locale: 'sk-SK',
        androidCode: 'sk-rSK',
        osxCode: 'sk.lproj',
        osxLocale: 'sk',
    },
    {
        name: 'Slovenian',
        twoLettersCode: 'sl',
        threeLettersCode: 'slv',
        locale: 'sl-SI',
        androidCode: 'sl-rSI',
        osxCode: 'sl.lproj',
        osxLocale: 'sl',
    },
    {
        name: 'Somali',
        twoLettersCode: 'so',
        threeLettersCode: 'som',
        locale: 'so-SO',
        androidCode: 'so-rSO',
        osxCode: 'so.lproj',
        osxLocale: 'so',
    },
    {
        name: 'Songhay',
        twoLettersCode: 'son',
        threeLettersCode: 'son',
        locale: 'son-ZA',
        androidCode: 'son-rZA',
        osxCode: 'son.lproj',
        osxLocale: 'son',
    },
    {
        name: 'Sorani (Kurdish)',
        twoLettersCode: 'ku',
        threeLettersCode: 'ckb',
        locale: 'ckb-IR',
        androidCode: 'ckb-rIR',
        osxCode: 'ckb.lproj',
        osxLocale: 'ckb',
    },
    {
        name: 'Southern Ndebele',
        twoLettersCode: 'nr',
        threeLettersCode: 'nbl',
        locale: 'nr-ZA',
        androidCode: 'nr-rZA',
        osxCode: 'nr.lproj',
        osxLocale: 'nr',
    },
    {
        name: 'Southern Sami',
        twoLettersCode: 'sma',
        threeLettersCode: 'sma',
        locale: 'sma-NO',
        androidCode: 'sma-rNO',
        osxCode: 'sma.lproj',
        osxLocale: 'sma',
    },
    {
        name: 'Southern Sotho',
        twoLettersCode: 'st',
        threeLettersCode: 'sot',
        locale: 'st-ZA',
        androidCode: 'st-rZA',
        osxCode: 'st.lproj',
        osxLocale: 'st',
    },
    {
        name: 'Spanish',
        twoLettersCode: 'es',
        threeLettersCode: 'spa',
        locale: 'es-ES',
        androidCode: 'es-rES',
        osxCode: 'es.lproj',
        osxLocale: 'es',
    },
    {
        name: 'Spanish (Modern)',
        twoLettersCode: 'es',
        threeLettersCode: 'spa',
        locale: 'es-EM',
        androidCode: 'es-rEM',
        osxCode: 'es-EM.lproj',
        osxLocale: 'es_EM',
    },
    {
        name: 'Spanish, Argentina',
        twoLettersCode: 'es',
        threeLettersCode: 'spa',
        locale: 'es-AR',
        androidCode: 'es-rAR',
        osxCode: 'es-AR.lproj',
        osxLocale: 'es_AR',
    },
    {
        name: 'Spanish, Bolivia',
        twoLettersCode: 'es',
        threeLettersCode: 'spa',
        locale: 'es-BO',
        androidCode: 'es-rBO',
        osxCode: 'es-BO.lproj',
        osxLocale: 'es_BO',
    },
    {
        name: 'Spanish, Chile',
        twoLettersCode: 'es',
        threeLettersCode: 'spa',
        locale: 'es-CL',
        androidCode: 'es-rCL',
        osxCode: 'es-CL.lproj',
        osxLocale: 'es_CL',
    },
    {
        name: 'Spanish, Colombia',
        twoLettersCode: 'es',
        threeLettersCode: 'spa',
        locale: 'es-CO',
        androidCode: 'es-rCO',
        osxCode: 'es-CO.lproj',
        osxLocale: 'es_CO',
    },
    {
        name: 'Spanish, Costa Rica',
        twoLettersCode: 'es',
        threeLettersCode: 'spa',
        locale: 'es-CR',
        androidCode: 'es-rCR',
        osxCode: 'es-CR.lproj',
        osxLocale: 'es_CR',
    },
    {
        name: 'Spanish, Dominican Republic',
        twoLettersCode: 'es',
        threeLettersCode: 'spa',
        locale: 'es-DO',
        androidCode: 'es-rDO',
        osxCode: 'es-DO.lproj',
        osxLocale: 'es_DO',
    },
    {
        name: 'Spanish, Ecuador',
        twoLettersCode: 'es',
        threeLettersCode: 'spa',
        locale: 'es-EC',
        androidCode: 'es-rEC',
        osxCode: 'es-EC.lproj',
        osxLocale: 'es_EC',
    },
    {
        name: 'Spanish, El Salvador',
        twoLettersCode: 'es',
        threeLettersCode: 'spa',
        locale: 'es-SV',
        androidCode: 'es-rSV',
        osxCode: 'es-SV.lproj',
        osxLocale: 'es_SV',
    },
    {
        name: 'Spanish, Guatemala',
        twoLettersCode: 'es',
        threeLettersCode: 'spa',
        locale: 'es-GT',
        androidCode: 'es-rGT',
        osxCode: 'es-GT.lproj',
        osxLocale: 'es_GT',
    },
    {
        name: 'Spanish, Honduras',
        twoLettersCode: 'es',
        threeLettersCode: 'spa',
        locale: 'es-HN',
        androidCode: 'es-rHN',
        osxCode: 'es-HN.lproj',
        osxLocale: 'es_HN',
    },
    {
        name: 'Spanish, Mexico',
        twoLettersCode: 'es',
        threeLettersCode: 'spa',
        locale: 'es-MX',
        androidCode: 'es-rMX',
        osxCode: 'es-MX.lproj',
        osxLocale: 'es_MX',
    },
    {
        name: 'Spanish, Nicaragua',
        twoLettersCode: 'es',
        threeLettersCode: 'spa',
        locale: 'es-NI',
        androidCode: 'es-rNI',
        osxCode: 'es-NI.lproj',
        osxLocale: 'es_NI',
    },
    {
        name: 'Spanish, Panama',
        twoLettersCode: 'es',
        threeLettersCode: 'spa',
        locale: 'es-PA',
        androidCode: 'es-rPA',
        osxCode: 'es-PA.lproj',
        osxLocale: 'es_PA',
    },
    {
        name: 'Spanish, Paraguay',
        twoLettersCode: 'es',
        threeLettersCode: 'spa',
        locale: 'es-PY',
        androidCode: 'es-rPY',
        osxCode: 'es-PY.lproj',
        osxLocale: 'es_PY',
    },
    {
        name: 'Spanish, Peru',
        twoLettersCode: 'es',
        threeLettersCode: 'spa',
        locale: 'es-PE',
        androidCode: 'es-rPE',
        osxCode: 'es-PE.lproj',
        osxLocale: 'es_PE',
    },
    {
        name: 'Spanish, Puerto Rico',
        twoLettersCode: 'es',
        threeLettersCode: 'spa',
        locale: 'es-PR',
        androidCode: 'es-rPR',
        osxCode: 'es-PR.lproj',
        osxLocale: 'es_PR',
    },
    {
        name: 'Spanish, United States',
        twoLettersCode: 'es',
        threeLettersCode: 'spa',
        locale: 'es-US',
        androidCode: 'es-rUS',
        osxCode: 'es-US.lproj',
        osxLocale: 'es_US',
    },
    {
        name: 'Spanish, Uruguay',
        twoLettersCode: 'es',
        threeLettersCode: 'spa',
        locale: 'es-UY',
        androidCode: 'es-rUY',
        osxCode: 'es-UY.lproj',
        osxLocale: 'es_UY',
    },
    {
        name: 'Spanish, Venezuela',
        twoLettersCode: 'es',
        threeLettersCode: 'spa',
        locale: 'es-VE',
        androidCode: 'es-rVE',
        osxCode: 'es-VE.lproj',
        osxLocale: 'es_VE',
    },
    {
        name: 'Sundanese',
        twoLettersCode: 'su',
        threeLettersCode: 'sun',
        locale: 'su-ID',
        androidCode: 'su-rID',
        osxCode: 'su.lproj',
        osxLocale: 'su',
    },
    {
        name: 'Swahili',
        twoLettersCode: 'sw',
        threeLettersCode: 'swa',
        locale: 'sw-KE',
        androidCode: 'sw-rKE',
        osxCode: 'sw.lproj',
        osxLocale: 'sw',
    },
    {
        name: 'Swahili, Kenya',
        twoLettersCode: 'sw',
        threeLettersCode: 'swa',
        locale: 'sw-KE',
        androidCode: 'sw-rKE',
        osxCode: 'sw-KE.lproj',
        osxLocale: 'sw_KE',
    },
    {
        name: 'Swahili, Tanzania',
        twoLettersCode: 'sw',
        threeLettersCode: 'swa',
        locale: 'sw-TZ',
        androidCode: 'sw-rTZ',
        osxCode: 'sw-TZ.lproj',
        osxLocale: 'sw_TZ',
    },
    {
        name: 'Swati',
        twoLettersCode: 'ss',
        threeLettersCode: 'ssw',
        locale: 'ss-ZA',
        androidCode: 'ss-rZA',
        osxCode: 'ss.lproj',
        osxLocale: 'ss',
    },
    {
        name: 'Swedish',
        twoLettersCode: 'sv',
        threeLettersCode: 'swe',
        locale: 'sv-SE',
        androidCode: 'sv-rSE',
        osxCode: 'sv.lproj',
        osxLocale: 'sv',
    },
    {
        name: 'Swedish, Finland',
        twoLettersCode: 'sv',
        threeLettersCode: 'swe',
        locale: 'sv-FI',
        androidCode: 'sv-rFI',
        osxCode: 'sv-FI.lproj',
        osxLocale: 'sv_FI',
    },
    {
        name: 'Syriac',
        twoLettersCode: 'syc',
        threeLettersCode: 'syc',
        locale: 'syc-SY',
        androidCode: 'syc-rSY',
        osxCode: 'syc.lproj',
        osxLocale: 'syc',
    },
    {
        name: 'Tagalog',
        twoLettersCode: 'tl',
        threeLettersCode: 'tgl',
        locale: 'tl-PH',
        androidCode: 'tl-rPH',
        osxCode: 'tl.lproj',
        osxLocale: 'tl',
    },
    {
        name: 'Tahitian',
        twoLettersCode: 'ty',
        threeLettersCode: 'tah',
        locale: 'ty-PF',
        androidCode: 'ty-rPF',
        osxCode: 'ty.lproj',
        osxLocale: 'ty',
    },
    {
        name: 'Tajik',
        twoLettersCode: 'tg',
        threeLettersCode: 'tgk',
        locale: 'tg-TJ',
        androidCode: 'tg-rTJ',
        osxCode: 'tg.lproj',
        osxLocale: 'tg',
    },
    {
        name: 'Tamil',
        twoLettersCode: 'ta',
        threeLettersCode: 'tam',
        locale: 'ta-IN',
        androidCode: 'ta-rIN',
        osxCode: 'ta.lproj',
        osxLocale: 'ta',
    },
    {
        name: 'Tatar',
        twoLettersCode: 'tt',
        threeLettersCode: 'tat',
        locale: 'tt-RU',
        androidCode: 'tt-rRU',
        osxCode: 'tt.lproj',
        osxLocale: 'tt',
    },
    {
        name: 'Telugu',
        twoLettersCode: 'te',
        threeLettersCode: 'tel',
        locale: 'te-IN',
        androidCode: 'te-rIN',
        osxCode: 'te.lproj',
        osxLocale: 'te',
    },
    {
        name: 'Tem (Kotokoli)',
        twoLettersCode: 'kdh',
        threeLettersCode: 'kdh',
        locale: 'kdh-KDH',
        androidCode: 'kdh-rKDH',
        osxCode: 'kdh.lproj',
        osxLocale: 'kdh',
    },
    {
        name: 'Thai',
        twoLettersCode: 'th',
        threeLettersCode: 'tha',
        locale: 'th-TH',
        androidCode: 'th-rTH',
        osxCode: 'th.lproj',
        osxLocale: 'th',
    },
    {
        name: 'Tibetan',
        twoLettersCode: 'bo',
        threeLettersCode: 'tib',
        locale: 'bo-BT',
        androidCode: 'bo-rBT',
        osxCode: 'bo.lproj',
        osxLocale: 'bo',
    },
    {
        name: 'Tigrinya',
        twoLettersCode: 'ti',
        threeLettersCode: 'tir',
        locale: 'ti-ER',
        androidCode: 'ti-rER',
        osxCode: 'ti.lproj',
        osxLocale: 'ti',
    },
    {
        name: 'Tsonga',
        twoLettersCode: 'ts',
        threeLettersCode: 'tso',
        locale: 'ts-ZA',
        androidCode: 'ts-rZA',
        osxCode: 'ts.lproj',
        osxLocale: 'ts',
    },
    {
        name: 'Tswana',
        twoLettersCode: 'tn',
        threeLettersCode: 'tsn',
        locale: 'tn-ZA',
        androidCode: 'tn-rZA',
        osxCode: 'tn.lproj',
        osxLocale: 'tn',
    },
    {
        name: 'Turkish',
        twoLettersCode: 'tr',
        threeLettersCode: 'tur',
        locale: 'tr-TR',
        androidCode: 'tr-rTR',
        osxCode: 'tr.lproj',
        osxLocale: 'tr',
    },
    {
        name: 'Turkish, Cyprus',
        twoLettersCode: 'tr',
        threeLettersCode: 'tur',
        locale: 'tr-CY',
        androidCode: 'tr-rCY',
        osxCode: 'tr-CY.lproj',
        osxLocale: 'tr_CY',
    },
    {
        name: 'Turkmen',
        twoLettersCode: 'tk',
        threeLettersCode: 'tuk',
        locale: 'tk-TM',
        androidCode: 'tk-rTM',
        osxCode: 'tk.lproj',
        osxLocale: 'tk',
    },
    {
        name: 'Ukrainian',
        twoLettersCode: 'uk',
        threeLettersCode: 'ukr',
        locale: 'uk-UA',
        androidCode: 'uk-rUA',
        osxCode: 'uk.lproj',
        osxLocale: 'uk',
    },
    {
        name: 'Upper Sorbian',
        twoLettersCode: 'hsb',
        threeLettersCode: 'hsb',
        locale: 'hsb-DE',
        androidCode: 'hsb-rDE',
        osxCode: 'hsb.lproj',
        osxLocale: 'hsb',
    },
    {
        name: 'Urdu (India)',
        twoLettersCode: 'ur',
        threeLettersCode: 'urd',
        locale: 'ur-IN',
        androidCode: 'ur-rIN',
        osxCode: 'ur-IN.lproj',
        osxLocale: 'ur_IN',
    },
    {
        name: 'Urdu (Pakistan)',
        twoLettersCode: 'ur',
        threeLettersCode: 'urd',
        locale: 'ur-PK',
        androidCode: 'ur-rPK',
        osxCode: 'ur.lproj',
        osxLocale: 'ur',
    },
    {
        name: 'Uyghur',
        twoLettersCode: 'ug',
        threeLettersCode: 'uig',
        locale: 'ug-CN',
        androidCode: 'ug-rCN',
        osxCode: 'ug.lproj',
        osxLocale: 'ug',
    },
    {
        name: 'Uzbek',
        twoLettersCode: 'uz',
        threeLettersCode: 'uzb',
        locale: 'uz-UZ',
        androidCode: 'uz-rUZ',
        osxCode: 'uz.lproj',
        osxLocale: 'uz',
    },
    {
        name: 'Valencian',
        twoLettersCode: 'val',
        threeLettersCode: 'val',
        locale: 'val-ES',
        androidCode: 'val-rES',
        osxCode: 'val.lproj',
        osxLocale: 'val',
    },
    {
        name: 'Venda',
        twoLettersCode: 've',
        threeLettersCode: 'ven',
        locale: 've-ZA',
        androidCode: 've-rZA',
        osxCode: 've.lproj',
        osxLocale: 've',
    },
    {
        name: 'Venetian',
        twoLettersCode: 'vec',
        threeLettersCode: 'vec',
        locale: 'vec-IT',
        androidCode: 'vec-rIT',
        osxCode: 'vec.lproj',
        osxLocale: 'vec',
    },
    {
        name: 'Vietnamese',
        twoLettersCode: 'vi',
        threeLettersCode: 'vie',
        locale: 'vi-VN',
        androidCode: 'vi-rVN',
        osxCode: 'vi.lproj',
        osxLocale: 'vi',
    },
    {
        name: 'Walloon',
        twoLettersCode: 'wa',
        threeLettersCode: 'wln',
        locale: 'wa-BE',
        androidCode: 'wa-rBE',
        osxCode: 'wa.lproj',
        osxLocale: 'wa',
    },
    {
        name: 'Welsh',
        twoLettersCode: 'cy',
        threeLettersCode: 'cym',
        locale: 'cy-GB',
        androidCode: 'cy-rGB',
        osxCode: 'cy.lproj',
        osxLocale: 'cy',
    },
    {
        name: 'Wolof',
        twoLettersCode: 'wo',
        threeLettersCode: 'wol',
        locale: 'wo-SN',
        androidCode: 'wo-rSN',
        osxCode: 'wo.lproj',
        osxLocale: 'wo',
    },
    {
        name: 'Xhosa',
        twoLettersCode: 'xh',
        threeLettersCode: 'xho',
        locale: 'xh-ZA',
        androidCode: 'xh-rZA',
        osxCode: 'xh.lproj',
        osxLocale: 'xh',
    },
    {
        name: 'Yiddish',
        twoLettersCode: 'yi',
        threeLettersCode: 'yid',
        locale: 'yi-DE',
        androidCode: 'ji-rDE',
        osxCode: 'yi.lproj',
        osxLocale: 'yi',
    },
    {
        name: 'Yoruba',
        twoLettersCode: 'yo',
        threeLettersCode: 'yor',
        locale: 'yo-NG',
        androidCode: 'yo-rNG',
        osxCode: 'yo.lproj',
        osxLocale: 'yo',
    },
    {
        name: 'Zeelandic',
        twoLettersCode: 'zea',
        threeLettersCode: 'zea',
        locale: 'zea-ZEA',
        androidCode: 'zea-rZEA',
        osxCode: 'zea.lproj',
        osxLocale: 'zea',
    },
    {
        name: 'Zulu',
        twoLettersCode: 'zu',
        threeLettersCode: 'zul',
        locale: 'zu-ZA',
        androidCode: 'zu-rZA',
        osxCode: 'zu.lproj',
        osxLocale: 'zu',
    },
];

export function includesLanguagePlaceholders(str: string): boolean {
    return Object.keys(languagePlaceholders).some(placeholder => str.includes(placeholder));
}

export function replaceLanguagePlaceholders(
    str: string,
    languageCode: string,
    languageMapping?: LanguageMapping,
): string {
    const language = languages.find(l => l.twoLettersCode === languageCode || l.locale === languageCode);
    if (!language) {
        throw new Error(`Unsupported language code : ${languageCode}`);
    }
    let result = str;
    for (const placeholder of Object.keys(languagePlaceholders)) {
        if (result.includes(placeholder)) {
            const cleanPlaceholder = placeholder.slice(1, -1);
            const replaceValue =
                languageMapping && languageMapping[cleanPlaceholder]
                    ? languageMapping[cleanPlaceholder]
                    : languagePlaceholders[placeholder](language);
            result = result.replace(placeholder, replaceValue);
        }
    }
    return result;
}
