name: Documentation

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build_and_deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: |
            pnpm-lock.yaml
            website/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install docs dependencies
        working-directory: website
        run: pnpm install --frozen-lockfile

      - name: Create the docs directory locally in CI
        working-directory: website
        run: pnpm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
        with:
          branch: gh-pages
          folder: website/build
